### ISSUE TITLE
Functional Programming & Architecture in ES6

### ISSUE THREAD

**Issue by dialelo** [BarcelonaJS/BarcelonaJS#1]
---

level: advanced
language: en
twitter: dialelo
tags:
  - functional programming
  - react
  - arquitecture

---

In this talk we'll explore the innovation that has happened in the ClojureScript community
for building applications in the browser and how we can leverage such ideas and the
functional programming paradigm in JavaScript.

We'll see how virtual DOM implementations like React open up possibilities for a functional
architecture in our applications, which can be radically simpler than traditional approaches.
The main benefits are a sound separation of concerns, better reasoning about the systems we
design and the ability to easily test our applications.

The topics we'll cover include:

- Functional programming
- State management & immutability
- Error handling
- Communication & coordination using Communicating Sequential Processes
- Testing
- Recasting Flux using all of the above

The talk will be based on a project that I'm currently working on using the aforementioned
ideas and techniques.

**Comment by danicomas** [comment]
+1

**Comment by juliangamble** [comment]
Will the talk be recorded or the slides available?

**Comment by dialelo** [comment]
Don't know about the recording but slides are [already available online](http://dialelo.github.io/talks/functional-programming-and-architecture-in-javascript/#1).
