### ISSUE TITLE
Angular 2 Alpha 47

### ISSUE THREAD

**Issue by Elecash** [BarcelonaJS/BarcelonaJS#10]
---
level: beginner
language: en | es
twitter: elecash
tags:
  - angular2
  - web components
  - javascript

---
Creating an Angular 2 (Alpha 46) app that works.

**Comment by orestes** [comment]
+1 :smile: 
We want new stuff.

**Comment by eth0lo** [comment]
it would be ok for dec? @Elecash

**Comment by Elecash** [comment]
For december would be great :) @eth0lo

**Comment by dgil** [comment]
👌😀

**Comment by Elecash** [comment]
Alpha 47 was released yesteday, so I've changed the topic :)
