### ISSUE TITLE
Meetup January 12, 2016

### ISSUE THREAD

**Issue by substack** [BarcelonaJS/BarcelonaJS#2]
---
address: C/ Fontella 2, 08001, Barcelona
date: 12.01.2016
name: BarcelonaJS
venue: Mobile World Centre

---

## Checklist
* [ ] MC (Master of Ceremony)
* [ ] Registration - 
* [ ] Website - 
* [ ] Meetup.com
* [ ] Mailing List - 
* [ ] Video & YouTube - 
* [ ] Twitter - 
* [ ] Speakers - 
* [ ] Sponsors
* [ ] Hot Issue's - 
* [ ] Venue - 

@BarcelonaJS/barcelonajs

**Comment by PatrickHeneise** [comment]
Awesome, thanks! We're meeting Wednesday, Sep 9, 6.45pm at the Mobile World Centre directly at Placa Catalunya, 2nd floor.
