### ISSUE TITLE
Sound Synthesis with Web Audio

### ISSUE THREAD

**Issue by lcrespom** [BarcelonaJS/BarcelonaJS#20]
---
level: interesting for beginners and experts
language: English or Spanish, depending on the audience preference
twitter: @lcrespom
tags:
  - WebAudio
  - SoundSynthesis
  - HTML5

---

Computers have always been a great tool for creating music. Until recently, the web platform was limited to playing back recorded sounds, but the Web Audio API provides very powerful and versatile sound synthesis capabilities.

In this talk I will give an introduction to computer sound synthesis, present the Web Audio API, perform some live coding, and demo a complete graphical synthesizer created with Web Audio.

**Comment by lcrespom** [comment]
Does this mean accepted or rejected?

**Comment by eth0lo** [comment]
I think it should not be close .... And would be good if you can there on January 13

**Comment by eth0lo** [comment]
I @PatrickHeneise is playing with git-events and mistakenly closed this

**Comment by PatrickHeneise** [comment]
I'm not playing and it's not a mistake. It's in barcelonajs/speakers now.

**Comment by lcrespom** [comment]
Oh, I just noticed it is the old issue, sorry
