### ISSUE TITLE
The Universal Datatype

### ISSUE THREAD

**Issue by sergi** [BarcelonaJS/BarcelonaJS#29]
---
level: advanced
language: en
twitter: @sergimansilla
tags:
  - rxjs
  - reactive
  - javascript

---

In this talk I'll introduce reactive programming using RxJS and it's central concept: the Observable Sequence. Observable sequences give developers super-powers by letting you manage asynchronous code with ease, and think about complex flows of events as if they were all synchronous, abstracting time in a way you've never seen before. You can think of it as a simpler Promise, but on steroids. I'll show you some cool programs and examples straight from my Reactive Programming book, and if there is time, I might try to even do some live-coding!

**Comment by PatrickHeneise** [comment]
Sorry, could you please copy over the talk to the speakers repo https://github.com/BarcelonaJS/speakers? Thanks!

**Comment by PatrickHeneise** [comment]
@sergi I'd appreciate if you could copy over the talk as I can't do it.

**Comment by dgil** [comment]
@sergi are you interested in presenting this talk in the February meetup? If so, please create the issue in https://github.com/BarcelonaJS/speakers repository.

Thank you

**Comment by sergi** [comment]
Hi @PatrickHeneise @dgil, sorry I didn't see the notification for this. I'll do that now.
