### ISSUE TITLE
Meetup: BarcelonaJS January 2016

### ISSUE THREAD

**Issue by somebody32** [BarcelonaJS/BarcelonaJS#3]
---
address: C/ Fontella 2, 08001, Barcelona
date: 12.01.2016
name: BarcelonaJS January 2016
venue: Mobile World Centre

---

## Checklist
* [ ] MC (Master of Ceremony) -
* [ ] Registration - 
* [ ] Website - 
* [ ] Meetup.com
* [ ] Mailing List - 
* [ ] Video & YouTube - 
* [ ] Twitter - 
* [ ] Speakers - 
* [ ] Sponsors
* [ ] Hot Issue's - 
* [ ] Venue - 

@BarcelonaJS/barcelonajs

**Comment by PatrickHeneise** [comment]
shit, bot went nuts :( sorry
