### ISSUE TITLE
TypeScript will finally bring peace to your troubled soul

### ISSUE THREAD

**Issue by pimterry** [BarcelonaJS/BarcelonaJS#4]
---
address: C/ Fontella 2, 08001, Barcelona
date: 10.02.2016
name: BarcelonaJS February 2016
venue: Mobile World Centre

---

## Checklist
* [ ] MC (Master of Ceremony) -
* [ ] Registration - 
* [ ] Website - 
* [ ] Meetup.com
* [ ] Mailing List - 
* [ ] Video & YouTube - 
* [ ] Twitter - 
* [ ] Speakers - 
* [ ] Sponsors
* [ ] Hot Issue's - 
* [ ] Venue - 

@BarcelonaJS/barcelonajs

**Comment by pimterry** [comment]
Ah, you've put 'accepted' on this. You totally don't get notifications for labels like that (or maybe I've turned them off), I had no idea this was definitely happening!

No problem though, that's good to hear, I'll stick in in the diary now.

**Comment by PatrickHeneise** [comment]
mhm, good to know. Will use @-comments in the future to remind people.

**Comment by PatrickHeneise** [comment]
sorry, gitevents bug :(
