### ISSUE TITLE
Advanced CSS (make your own bootstrap)

### ISSUE THREAD

**Issue by rnowm** [BarcelonaJS/BarcelonaJS#7]
Not JS, but I guess your projects also have styles!
I could give that talk if you are interested :)

**Comment by Elecash** [comment]
+1 for this one, I really think that @BcnJS should have more CSS talks

**Comment by PatrickHeneise** [comment]
@Elecash @rnowm could you go into more detail what you would cover/expect from the talk?

**Comment by ifraixedes** [comment]
There is a lot of tooling written in JS for CSS stuff

@jgnatch talked about CSS Modules which are quite good approach to have better CSS management for writing web components to keep encapsulations and isolation.

The most of the tooling for that kind of stuff is, today, written in node; for example postcss have so many plugins to do tons of new things.

So I believe that we can have good talks of CSS.

I hope that this comments could help to give a description of the talk which gather the interests of the community.

**Comment by rnowm** [comment]
Sorry for not answering before, my gh notifications are muted :) 
I could do something like this:
http://rnowm.github.io/bootstrapU/1.html
Talking about pros and cons of css frameworks.

**Comment by ifraixedes** [comment]
Could you add, if you have experience on, in how styles and layouts impact in painting performance?

Some people like me, we spend our main time in JS like so we don't have that much knowledge about; we have sometimes to build HTML and CSS and we are quite clear in what to worry in terms of JS execution and browser API calls to avoid bad performance, however we usually wonder (or at least I do) if the HTML has the right structure and CSS is well structure to avoid painting bottle necks obtaining similar results. I totally understand that it depends of the dynamism of the site (animations, etc) but I don't know if there are things to avoid as much as we can to get a performance boost.

**Comment by rnowm** [comment]
Sure I could :)
