### ISSUE TITLE
Angular 1.5 components

### ISSUE THREAD

**Issue by Elecash** [BarcelonaJS/BarcelonaJS#9]
---
level: advanced
language: en | es
twitter: elecash
tags:
  - angular 1.5
  - components
  - directives
  - javascript

Learn how to use in Angular 1.5 the new component feature to create future-proof directives that can be migrated easily to Angular 2.

**Comment by PatrickHeneise** [comment]
@Elecash Please copy to BarcelonaJS/speakers
